home/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'home'
urlpatterns = [
    path('', views.home , name="home"),
    path('homework/',views.homeworks, name="homeworks"),
    path('homework_upload/',views.upload, name="upload"),
    path('homework/<id>/', views.homework , name="homework"),
]

jamal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from PIL import Image
# Create your models here.
class allhomeworks(models.Model):
    title = models.CharField(verbose_name=_("homework title"), max_length=50)
    date = models.DateTimeField(auto_now_add=True , auto_now=False)
    desc = models.TextField(verbose_name=_("Description"))
    image = models.ImageField(default='default.jpg')
    img1 = models.ImageField(_("exercice"), null=True)
    img2 = models.ImageField(_("solution"), null=True)
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.image.path)
        width, height = img.size  # Get dimensions

        if width > 300 and height > 300:
            # keep ratio but shrink down
            img.thumbnail((width, height))

        # check which one is smaller
        if height < width:
            # make square by cutting off equal amounts left and right
            left = (width - height) / 2
            right = (width + height) / 2
            top = 0
            bottom = height
            img = img.crop((left, top, right, bottom))

        elif width < height:
            # make square by cutting off bottom
            left = 0
            right = width
            top = 0
            bottom = width
            img = img.crop((left, top, right, bottom))

        if width > 300 and height > 300:
            img.thumbnail((300, 300))

        img.save(self.image.path)
    class Meta:
        verbose_name = _("homework")

home/forms.py
from django.db import models
from django import forms
from .models import allhomeworks


class Homeworkform(forms.ModelForm):
    title = forms.CharField(max_length=50 , widget=forms.TextInput (attrs={'class':'','placeholder':'Enter your homework title ...'}))
    desc = forms.CharField(widget=forms.Textarea (attrs={'class':'','placeholder':'Enter your homework desc ...'}))
    image = forms.ImageField()
    class Meta:
        model = allhomeworks
        fields = '__all__'
        exclude = ('date',)

home/views.py
from django.shortcuts import render,get_object_or_404
from .models import allhomeworks
from django.contrib import messages
from django.utils.translation import gettext as _
from .forms import Homeworkform
# Create your views here.
def home(request):
    content={
        'homework': allhomeworks.objects.all(),
    }
    return render(request, 'home/index.html', content)

def homework(request, id): 
    homeworkz= get_object_or_404(allhomeworks, id=id)
    content={
        'homework': homeworkz,
    }
    return render(request, 'home/homework.html',content)

def homeworks(request):
    content={
        'homework': allhomeworks.objects.all(),
    }
    return render(request,'home/homeworks.html',content)
def upload(request):
    if request.method == 'POST':
        homework_upload(request.POST)
        if homework_upload.is_valid:
            homework_upload.save()
    else:
        homework_upload = Homeworkform()

    context={
        'Uwu':homework_upload,
    }
    return render(request, 'home/upload.html',context)

home/templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Hello , My name is Jamal this is My homework showcase">
    <title>HomeWork</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="{% static 'style.css' %}" rel="stylesheet">
  </head>
  <body>
      {% block content %}{% endblock content %}

      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
      <script src="{% static 'main.js' %}"></script>
  </body>
</html>

home/templates/home/homework.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<section class="homeright">
    <div class="row">
        <div class="col-6 col-md-4">
            {{ homework.desc }}
        </div>
        <div class="col-md-8">
            <div class="hereis">
                <h1>{{ homework.title }}</h1>
            </div>
            <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <img src="{{ homework.img1.url }}" class="card-img homim" alt="...">
                <img src="{{ homework.img2.url }}" class="card-img homim" alt="...">
            </div>
        </div>
      </div>
</section>
<div class="d-grid gap-2">
    <button class="btn btn-primary" type="button"><a href="/">go back</a></button>
</div>
{% endblock content %}

home/templates/home/homeworks.html
{% extends 'home/base.html' %}
{% block content %}
<h1></h1>
{% endblock content %}

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<header>
    <nav class="navbar">
        <ul class="it">
            <li><a href="/">Home</a></li>
            <li><a href="#homeworkss">HomeWorks</a></li>
            <li>Contact</li>
            <li class="logoo">Homework</li>
        </ul>
    </nav>
</header>
<section class="hello">
    <div class="thep">
        Welcome back..!
    </div>
    <div class="btns">
        <a class="view hbtn" href="#homeworkss">View homework</a>
        <a class="upload hbtn" href="/homework_upload/">Upload homework</a>
    </div>
</section>
<section class="hwork" id="homeworkss">
<div class="row row-cols-1 row-cols-md-4 g-4">
{% for homework in homework %}
  <div class="col">
    <div class="card">
      <a href="{% url 'home:homework' homework.id  %}"><img src="{{ homework.image.url }}" class="card-img-top" alt="..."></a>
      <div class="card-body">
        <h5 class="card-title">{{ homework.title }}</h5>
        <p class="card-text descri">{{ homework.desc }}</p>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
</section>
{% endblock content %}

home/templates/home/upload.html
{% extends 'home/base.html' %}
{% load static %}
{% block content %}
<h1 class="ptitle">add new homework</h1>
<div class="misform">
    <form method="POST">
    {% csrf_token %}
    <div class="mb-3">
    <label for="exampleFormControlInput1" class="form-label">homework title</label>
    {{ Uwu.title }}
    </div>
    <div class="mb-3">
    <label for="exampleFormControlTextarea1" class="form-label">description</label>
    {{ Uwu.desc }}
    </div>
    <div class="mb-3">
    <label for="formFile" class="form-label">Homework image</label>
        {{ Uwu.image }}
    </div>
    <div class="mb-3">
    <label for="formFile" class="form-label">exercice</label>
        {{ Uwu.img1 }}
    </div>
    <div class="mb-3">
    <label for="formFile" class="form-label">solution</label>
        {{ Uwu.img2 }}
    </div>
    <div class="d-grid gap-2">
    <button class="btn btn-primary" type="submit">Button</button>
    <button class="btn btn-primary" type="button"><a href="/">go back</a></button>
    </div>
    </form>
</div>
<script>
document.getElementById('id_image').classList.add('form-control','classname2');
document.getElementById('id_img1').classList.add('form-control','form-control-sm')
document.getElementById('id_img2').classList.add('form-control','form-control-sm')
document.getElementById('id_desc').classList.add('form-control','descform')
document.getElementById('id_title').classList.add('form-control','')
</script>
{% endblock content %}